// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7lzZKg-Gr2jHomLuI9FHxGKocNVljhs',
    appId: '1:841733443080:web:7802297997af1a9aaf0bbd',
    messagingSenderId: '841733443080',
    projectId: 'expense-tracker-82ca9',
    authDomain: 'expense-tracker-82ca9.firebaseapp.com',
    storageBucket: 'expense-tracker-82ca9.firebasestorage.app',
    measurementId: 'G-52G05TXJMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC2EBTjBJggeiOvHVw05JhsQYTwlSNfiY',
    appId: '1:841733443080:android:32584f3f92de5d5caf0bbd',
    messagingSenderId: '841733443080',
    projectId: 'expense-tracker-82ca9',
    storageBucket: 'expense-tracker-82ca9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYsNXbEh3v9O3heH5GRQeTjC3pRiOm2AQ',
    appId: '1:841733443080:ios:8c5983e5a896a496af0bbd',
    messagingSenderId: '841733443080',
    projectId: 'expense-tracker-82ca9',
    storageBucket: 'expense-tracker-82ca9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYsNXbEh3v9O3heH5GRQeTjC3pRiOm2AQ',
    appId: '1:841733443080:ios:8c5983e5a896a496af0bbd',
    messagingSenderId: '841733443080',
    projectId: 'expense-tracker-82ca9',
    storageBucket: 'expense-tracker-82ca9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw7lzZKg-Gr2jHomLuI9FHxGKocNVljhs',
    appId: '1:841733443080:web:679d9264fdcddbb0af0bbd',
    messagingSenderId: '841733443080',
    projectId: 'expense-tracker-82ca9',
    authDomain: 'expense-tracker-82ca9.firebaseapp.com',
    storageBucket: 'expense-tracker-82ca9.firebasestorage.app',
    measurementId: 'G-E41XJ20CLL',
  );
}
